from __future__ import annotations

from graphblas import Vector


class Orderbook:
    def append(self, key: dict, arr: Vector) -> None: ...
    def remove(self, index: int) -> None: ...
    def get_at_index(self, index: int) -> tuple[dict, Vector]: ...
    def allocate_greedy(self, values: Vector) -> list[tuple[dict, Vector]]: ...

    @property
    def size(self) -> int: ...
    @property
    def length(self) -> int: ...
